import utils from "../../src/utils/utils.js";
import prisma from "../../src/utils/prisma.js";
import roleService from "../../src/services/roleService.js";
const globalPassword = "password";
const hashedPassword = await utils.hashPassword(globalPassword);

export let defaultUsers = [
  {
    email: "formateur@demo.com",
    password: hashedPassword,
    birthDate: new Date("1990-01-01"),
    birthName: "Dupont",
    birthPlace: "Le Havre",
    permisB: true,
    mutuelle: true,
    employer: "ifen",
    occupation: "secrétaire",
    firstName: "Carole",
    lastName: "Durand",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "madame",
    diploma: "BAC+3",
  },
  {
    email: "admin@demo.com",
    password: hashedPassword,
    birthDate: new Date("1993-02-02"),
    birthName: "Leblond",
    birthPlace: "Rouen",
    permisB: false,
    mutuelle: true,
    employer: "Veoneer",
    occupation: "développeur",
    firstName: "Julin",
    lastName: "Leblond",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "monsieur",
    diploma: "DUT",
  },
  {
    email: "superadmin@demo.com",
    password: hashedPassword,
    birthDate: new Date("1995-03-03"),
    birthName: "Hébert",
    birthPlace: "Caen",
    permisB: true,
    mutuelle: true,
    employer: "Safran",
    occupation: "technicienne",
    firstName: "Julie",
    lastName: "Hébert",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "madame",
    diploma: "BAC+5",
  },
];

export let defaultSuperAdmins = [
  {
    email: "superAdmin@demo.com",
    password: hashedPassword,
    birthDate: new Date("1990-01-01"),
    birthName: "Dupont",
    birthPlace: "Le Havre",
    permisB: true,
    mutuelle: true,
    employer: "ifen",
    occupation: "secrétaire",
    firstName: "Jean",
    lastName: "Superadmin",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "madame",
    diploma: "BAC+3",
  },
  {
    email: "superAdmin2@demo.com",
    password: hashedPassword,
    birthDate: new Date("1993-02-02"),
    birthName: "Leblond",
    birthPlace: "Rouen",
    permisB: false,
    mutuelle: true,
    employer: "Veoneer",
    occupation: "développeur",
    firstName: "Antoine",
    lastName: "Superadmin",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "monsieur",
    diploma: "DUT",
  },
  {
    email: "superadmin3@demo.com",
    password: hashedPassword,
    birthDate: new Date("1995-03-03"),
    birthName: "Hébert",
    birthPlace: "Caen",
    permisB: true,
    mutuelle: true,
    employer: "Safran",
    occupation: "technicienne",
    firstName: "Julie",
    lastName: "Superadmin",
    phone: "06 22 36 39",
    socialSecurity: "123456789123456",
    gender: "madame",
    diploma: "BAC+5",
  },
];
export let defaultAdmins = [
  {
    email: "michel.dupont@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1988-04-12"),
    birthName: "Dupont",
    birthPlace: "Le Havre",
    permisB: true,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Secrétaire administratif",
    firstName: "Michel",
    lastName: "Dupont",
    phone: "06 22 36 39 12",
    socialSecurity: "188045612345678",
    gender: "monsieur",
    diploma: "BAC+3",
  },
  {
    email: "sylvie.leblond@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1991-09-27"),
    birthName: "Leblond",
    birthPlace: "Rouen",
    permisB: false,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Responsable de formation",
    firstName: "Sylvie",
    lastName: "Leblond",
    phone: "06 17 45 82 93",
    socialSecurity: "291097812345612",
    gender: "madame",
    diploma: "Licence Professionnelle",
  },
  {
    email: "justine.hebert@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1994-06-18"),
    birthName: "Hébert",
    birthPlace: "Caen",
    permisB: true,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Assistante administrative",
    firstName: "Justine",
    lastName: "Hébert",
    phone: "06 48 92 17 55",
    socialSecurity: "294067812349911",
    gender: "madame",
    diploma: "BAC+5",
  },
];

export let defaultFormateurs = [
  {
    email: "etienne.moreau@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1985-11-03"),
    birthName: "Moreau",
    birthPlace: "Le Havre",
    permisB: true,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Formateur en travail social",
    firstName: "Étienne",
    lastName: "Moreau",
    phone: "06 41 27 83 10",
    socialSecurity: "185117812458790",
    gender: "monsieur",
    diploma: "Master Éducation et Formation",
  },
  {
    email: "nicolas.martin@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1989-02-14"),
    birthName: "Martin",
    birthPlace: "Rouen",
    permisB: true,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Formateur en informatique",
    firstName: "Nicolas",
    lastName: "Martin",
    phone: "06 58 92 61 77",
    socialSecurity: "189027812678545",
    gender: "monsieur",
    diploma: "DUT Informatique",
  },
  {
    email: "lea.boucher@ifen.fr",
    password: hashedPassword,
    birthDate: new Date("1993-05-21"),
    birthName: "Boucher",
    birthPlace: "Caen",
    permisB: true,
    mutuelle: true,
    employer: "IFEN",
    occupation: "Formatrice en communication",
    firstName: "Léa",
    lastName: "Boucher",
    phone: "06 73 11 54 92",
    socialSecurity: "293057812349233",
    gender: "madame",
    diploma: "Master Communication",
  },
];

export async function createUserSeeds(user, role, address) {
  const createdUser = await prisma.user.upsert({
    where: { email: user.email },
    update: {},
    create: {
      email: user.email,
      password: user.password,
      roleId: role.id,
      firstName: user.firstName,
      lastName: user.lastName,
      birthDate: user.birthDate,
      birthName: user.birthName,
      birthPlace: user.birthPlace,
      permisB: user.permisB,
      mutuelle: user.mutuelle,
      employer: user.employer,
      occupation: user.occupation,
      phone: user.phone,
      socialSecurity: user.socialSecurity,
      gender: user.gender,
      diploma: user.diploma,
      addressId: address.id,
    },
  });
  return createdUser;
}

export async function createSuperAdminSeeds(user, address) {
  const superAdminRole = await roleService.getRoleByName("SUPER_ADMIN");

  const createdUser = await prisma.user.upsert({
    where: { email: user.email },
    update: {},
    create: {
      email: user.email,
      password: user.password,
      roleId: superAdminRole.id,
      firstName: user.firstName,
      lastName: user.lastName,
      birthDate: user.birthDate,
      birthName: user.birthName,
      birthPlace: user.birthPlace,
      permisB: user.permisB,
      mutuelle: user.mutuelle,
      employer: user.employer,
      occupation: user.occupation,
      phone: user.phone,
      socialSecurity: user.socialSecurity,
      gender: user.gender,
      diploma: user.diploma,
      addressId: address.id,
    },
  });
  return createdUser;
}

export async function createAdminSeeds(user, address) {
  const adminRole = await roleService.getRoleByName("ADMIN");

  const createdUser = await prisma.user.upsert({
    where: { email: user.email },
    update: {},
    create: {
      email: user.email,
      password: user.password,
      roleId: adminRole.id,
      firstName: user.firstName,
      lastName: user.lastName,
      birthDate: user.birthDate,
      birthName: user.birthName,
      birthPlace: user.birthPlace,
      permisB: user.permisB,
      mutuelle: user.mutuelle,
      employer: user.employer,
      occupation: user.occupation,
      phone: user.phone,
      socialSecurity: user.socialSecurity,
      gender: user.gender,
      diploma: user.diploma,
      addressId: address.id,
    },
  });
  return createdUser;
}

export async function createFormateurSeeds(user, address) {
  const formateurRole = await roleService.getRoleByName("FORMATEUR");

  const createdUser = await prisma.user.upsert({
    where: { email: user.email },
    update: {},
    create: {
      email: user.email,
      password: user.password,
      roleId: formateurRole.id,
      firstName: user.firstName,
      lastName: user.lastName,
      birthDate: user.birthDate,
      birthName: user.birthName,
      birthPlace: user.birthPlace,
      permisB: user.permisB,
      mutuelle: user.mutuelle,
      employer: user.employer,
      occupation: user.occupation,
      phone: user.phone,
      socialSecurity: user.socialSecurity,
      gender: user.gender,
      diploma: user.diploma,
      addressId: address.id,
    },
  });
  return createdUser;
}
